-- ==============================================================================
-- SCRIPT DDL: SISTEMA DE RESERVAS TURISMOUQ
--
-- Leyenda de las restricciones que usamos:
--   PRIMARY KEY -> identifica cada fila de forma unica
--   FOREIGN KEY -> amarra una fila con la fila de otra tabla (integridad referencial)
--   NOT NULL    -> el dato es obligatorio
--   UNIQUE      -> el dato (o la combinacion de datos) no se puede repetir
--   CHECK       -> el dato solo puede tomar valores validos (rangos, listas, fechas)
-- ==============================================================================


-- ==============================================================================
-- 1. MUNICIPIO
-- Catalogo con los 12 municipios del Quindio. Cada alojamiento queda en uno.
-- ==============================================================================
CREATE TABLE MUNICIPIO (
    id_municipio NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PK
    nombre VARCHAR2(60) NOT NULL UNIQUE                                   -- no se repite el municipio
);


-- ==============================================================================
-- 2. TIPO_ALOJAMIENTO
-- Catalogo de tipos (finca cafetera, hotel, glamping, hostal, posada rural...).
-- Es una tabla aparte para poder agregar tipos nuevos sin tocar la estructura.
-- ==============================================================================
CREATE TABLE TIPO_ALOJAMIENTO (
    id_tipo NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- PK
    nombre VARCHAR2(40) NOT NULL UNIQUE,                                  -- no se repite el tipo
    descripcion VARCHAR2(200)                                             -- opcional
);


-- ==============================================================================
-- 3. ALOJAMIENTO
-- Los establecimientos turisticos. Cada uno pertenece a un municipio y a un tipo.
-- OJO: las estrellas las pone el mismo alojamiento, no son la calificacion real
-- (la calificacion real sale de las resenas de los clientes).
-- ==============================================================================
CREATE TABLE ALOJAMIENTO (
    id_alojamiento NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PK
    id_municipio NUMBER(3) NOT NULL,
    id_tipo NUMBER(2) NOT NULL,
    nombre_comercial VARCHAR2(120) NOT NULL,
    direccion VARCHAR2(200) NOT NULL,
    estrellas NUMBER(1) NOT NULL CHECK (estrellas BETWEEN 1 AND 5),         -- solo de 1 a 5
    telefono VARCHAR2(20),
    correo VARCHAR2(120) CHECK (correo IS NULL OR INSTR(correo, '@') > 1),  -- si hay correo, debe tener @
    activo CHAR(1) DEFAULT 'S' NOT NULL CHECK (activo IN ('S', 'N')),       -- S = activo, N = inactivo
    CONSTRAINT fk_aloj_municipio FOREIGN KEY (id_municipio) REFERENCES MUNICIPIO(id_municipio),
    CONSTRAINT fk_aloj_tipo FOREIGN KEY (id_tipo) REFERENCES TIPO_ALOJAMIENTO(id_tipo),
    -- en un mismo municipio no puede haber dos alojamientos con el mismo nombre
    CONSTRAINT uk_aloj_nombre UNIQUE (id_municipio, nombre_comercial),
    -- tiene que tener al menos una forma de contacto
    CONSTRAINT chk_aloj_contacto CHECK (telefono IS NOT NULL OR correo IS NOT NULL)
);


-- ==============================================================================
-- 4. HABITACION
-- Los espacios que se pueden reservar dentro de cada alojamiento.
-- El UNIQUE (id_habitacion, id_alojamiento) parece raro porque id_habitacion ya es PK,
-- pero sirve para que las tablas de reservas puedan amarrar la habitacion y la reserva
-- al MISMO alojamiento con una llave foranea compuesta (ver RESERVA_HABITACION).
-- ==============================================================================
CREATE TABLE HABITACION (
    id_habitacion NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- PK
    id_alojamiento NUMBER(5) NOT NULL,
    numero NUMBER(4) NOT NULL CHECK (numero > 0),
    capacidad NUMBER(2) NOT NULL CHECK (capacidad BETWEEN 1 AND 12),        -- maximo de huespedes
    tipo VARCHAR2(10) NOT NULL CHECK (tipo IN ('SENCILLA', 'DOBLE', 'SUITE', 'CABANA')),
    descripcion VARCHAR2(300),
    CONSTRAINT fk_hab_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES ALOJAMIENTO(id_alojamiento),
    -- regla de negocio: dos habitaciones del mismo alojamiento no comparten numero
    CONSTRAINT uk_hab_numero UNIQUE (id_alojamiento, numero),
    CONSTRAINT uk_hab_aloj UNIQUE (id_habitacion, id_alojamiento)
);


-- ==============================================================================
-- 5. TEMPORADA
-- Rangos de fechas con su nivel (ALTA, MEDIA o BAJA). Se define por anio:
-- "Semana Santa 2025" y "Semana Santa 2026" son dos filas distintas.
-- Que las temporadas no se solapen ni dejen huecos no se puede poner en un CHECK
-- (hay que comparar contra otras filas), por eso lo verificamos con una consulta
-- al final del script de carga.
-- ==============================================================================
CREATE TABLE TEMPORADA (
    id_temporada NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- PK
    nombre VARCHAR2(80) NOT NULL UNIQUE,
    nivel VARCHAR2(5) NOT NULL CHECK (nivel IN ('ALTA', 'MEDIA', 'BAJA')),
    anio NUMBER(4) NOT NULL CHECK (anio BETWEEN 2000 AND 2100),
    fecha_inicio DATE NOT NULL UNIQUE,                                      -- dos temporadas no empiezan el mismo dia
    fecha_fin DATE NOT NULL,
    CONSTRAINT chk_fechas_temporada CHECK (fecha_fin >= fecha_inicio)       -- el fin no puede ser antes del inicio
);


-- ==============================================================================
-- 6. TARIFA
-- Precio por noche de cada habitacion en cada temporada. Es la tabla puente
-- (muchos a muchos) entre HABITACION y TEMPORADA. No es un porcentaje fijo sobre un
-- precio base: cada alojamiento decide cuanto sube o baja en cada temporada.
-- La PK compuesta garantiza una sola tarifa por habitacion y temporada.
-- ==============================================================================
CREATE TABLE TARIFA (
    id_habitacion NUMBER(6) NOT NULL,
    id_temporada NUMBER(4) NOT NULL,
    valor_noche NUMBER(10) NOT NULL CHECK (valor_noche > 0),                -- precio en pesos, siempre positivo
    PRIMARY KEY (id_habitacion, id_temporada),                              -- PK compuesta
    CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion) REFERENCES HABITACION(id_habitacion),
    CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada) REFERENCES TEMPORADA(id_temporada)
);


-- ==============================================================================
-- 7. CLIENTE
-- Las personas que reservan. Pueden venir de cualquier ciudad o pais.
-- ==============================================================================
CREATE TABLE CLIENTE (
    id_cliente NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- PK
    tipo_documento VARCHAR2(3) NOT NULL CHECK (tipo_documento IN ('CC', 'CE', 'PAS')),
    numero_documento VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(80) NOT NULL,
    apellido VARCHAR2(80) NOT NULL,
    correo VARCHAR2(120) NOT NULL UNIQUE CHECK (INSTR(correo, '@') > 1),    -- un correo por cliente, con @
    telefono VARCHAR2(20),
    ciudad_origen VARCHAR2(60) NOT NULL,
    -- el mismo documento (tipo + numero) no puede estar registrado dos veces
    CONSTRAINT uk_cliente_doc UNIQUE (tipo_documento, numero_documento)
);


-- ==============================================================================
-- 8. RESERVA
-- Es la cabecera de la reserva: quien reserva, en que alojamiento, el rango general
-- de fechas y el estado. Las habitaciones van en RESERVA_HABITACION (asi una sola
-- reserva puede tener varias habitaciones).
-- id_alojamiento esta aqui para poder obligar, con llaves foraneas compuestas, a que
-- todas las habitaciones y servicios de la reserva sean del mismo alojamiento.
-- fecha_cancelacion solo se llena si la reserva esta CANCELADA; con ella se aplica la
-- regla del reembolso (80 % si se cancela con mas de 5 dias de anticipacion).
-- ==============================================================================
CREATE TABLE RESERVA (
    id_reserva NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- PK
    id_cliente NUMBER(6) NOT NULL,
    id_alojamiento NUMBER(5) NOT NULL,
    fecha_creacion DATE NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    estado VARCHAR2(10) NOT NULL CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')),
    fecha_cancelacion DATE,
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente),
    CONSTRAINT fk_reserva_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES ALOJAMIENTO(id_alojamiento),
    -- estos dos UNIQUE existen para que otras tablas puedan referenciar el par completo
    CONSTRAINT uk_reserva_aloj UNIQUE (id_reserva, id_alojamiento),
    CONSTRAINT uk_reserva_estado UNIQUE (id_reserva, estado),
    CONSTRAINT chk_reserva_fechas CHECK (check_out > check_in),             -- se sale despues de entrar
    CONSTRAINT chk_reserva_creacion CHECK (fecha_creacion <= check_in),     -- se reserva antes de llegar
    CONSTRAINT chk_reserva_cancel_fecha CHECK (fecha_cancelacion IS NULL OR fecha_cancelacion >= fecha_creacion),
    -- si esta CANCELADA tiene fecha de cancelacion; si no esta cancelada, no la tiene
    CONSTRAINT chk_reserva_cancel CHECK ((estado = 'CANCELADA' AND fecha_cancelacion IS NOT NULL)
                                      OR (estado <> 'CANCELADA' AND fecha_cancelacion IS NULL))
);


-- ==============================================================================
-- 9. RESERVA_HABITACION
-- Es el detalle de la reserva: una fila por cada habitacion reservada, con sus propias
-- fechas dentro del rango general. Resuelve que un grupo pueda reservar varias
-- habitaciones en una sola reserva.
-- valor_estadia es la suma de las noches con la tarifa de la temporada de cada noche
-- (si la estadia cruza dos temporadas, cada tramo se cobra con su tarifa). Se guarda
-- para que el precio no cambie si despues modifican la tarifa.
-- Las dos FK compuestas obligan a que reserva y habitacion sean del mismo alojamiento.
-- ==============================================================================
CREATE TABLE RESERVA_HABITACION (
    id_reserva_hab NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PK
    id_reserva NUMBER(8) NOT NULL,
    id_alojamiento NUMBER(5) NOT NULL,
    id_habitacion NUMBER(6) NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    num_huespedes NUMBER(2) NOT NULL CHECK (num_huespedes >= 1),
    valor_estadia NUMBER(12) DEFAULT 0 NOT NULL CHECK (valor_estadia >= 0),
    CONSTRAINT fk_reshab_reserva FOREIGN KEY (id_reserva, id_alojamiento) REFERENCES RESERVA(id_reserva, id_alojamiento),
    CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion, id_alojamiento) REFERENCES HABITACION(id_habitacion, id_alojamiento),
    -- la misma habitacion no se repite dentro de una misma reserva
    CONSTRAINT uk_reshab UNIQUE (id_reserva, id_habitacion),
    CONSTRAINT chk_reshab_fechas CHECK (check_out > check_in),
    CONSTRAINT chk_reshab_max_noches CHECK (check_out - check_in <= 30)     -- maximo 30 noches por habitacion
);


-- ==============================================================================
-- 10. PAGO
-- Los pagos o abonos de una reserva (puede tener varios: anticipo y saldo).
-- Un reembolso se registra como un pago con estado REEMBOLSADO.
-- ==============================================================================
CREATE TABLE PAGO (
    id_pago NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- PK
    id_reserva NUMBER(8) NOT NULL,
    fecha_pago DATE NOT NULL,
    monto NUMBER(12) NOT NULL CHECK (monto > 0),                            -- siempre positivo
    metodo VARCHAR2(20) NOT NULL CHECK (metodo IN ('TARJETA_CREDITO', 'TARJETA_DEBITO', 'PSE', 'TRANSFERENCIA', 'EFECTIVO')),
    estado VARCHAR2(12) NOT NULL CHECK (estado IN ('EXITOSO', 'FALLIDO', 'PENDIENTE', 'REEMBOLSADO')),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva)
);


-- ==============================================================================
-- 11. SERVICIO
-- Servicios complementarios (desayuno, tour del cafe, spa...). Cada servicio es de UN
-- alojamiento: el desayuno de un hotel es un servicio distinto al de otro hotel.
-- ==============================================================================
CREATE TABLE SERVICIO (
    id_servicio NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- PK
    id_alojamiento NUMBER(5) NOT NULL,
    nombre VARCHAR2(80) NOT NULL,
    descripcion VARCHAR2(300),
    precio NUMBER(10) NOT NULL CHECK (precio > 0),
    CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES ALOJAMIENTO(id_alojamiento),
    -- un alojamiento no ofrece dos servicios con el mismo nombre
    CONSTRAINT uk_servicio_nombre UNIQUE (id_alojamiento, nombre),
    CONSTRAINT uk_servicio_aloj UNIQUE (id_servicio, id_alojamiento)
);


-- ==============================================================================
-- 12. RESERVA_SERVICIO
-- Los servicios que se contratan dentro de una reserva: que dia se consumen, cuantas
-- unidades y a que precio (el precio se guarda para que no cambie despues).
-- La FK compuesta con SERVICIO obliga a que el servicio sea del mismo alojamiento
-- de la reserva.
-- ==============================================================================
CREATE TABLE RESERVA_SERVICIO (
    id_reserva_serv NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK
    id_reserva NUMBER(8) NOT NULL,
    id_alojamiento NUMBER(5) NOT NULL,
    id_servicio NUMBER(6) NOT NULL,
    fecha_servicio DATE NOT NULL,
    cantidad NUMBER(3) NOT NULL CHECK (cantidad >= 1),
    precio_unitario NUMBER(10) NOT NULL CHECK (precio_unitario >= 0),
    CONSTRAINT fk_resserv_reserva FOREIGN KEY (id_reserva, id_alojamiento) REFERENCES RESERVA(id_reserva, id_alojamiento),
    CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio, id_alojamiento) REFERENCES SERVICIO(id_servicio, id_alojamiento),
    -- el mismo servicio no se repite el mismo dia en la misma reserva
    CONSTRAINT uk_resserv UNIQUE (id_reserva, id_servicio, fecha_servicio)
);


-- ==============================================================================
-- 13. RESENA
-- La opinion del cliente sobre una estadia. Solo se puede resenar una reserva
-- COMPLETADA y una sola resena por reserva (id_reserva es UNIQUE).
-- Como estado_reserva siempre vale COMPLETADA (CHECK) y la FK compuesta lo compara con
-- el estado real de la reserva, la base de datos rechaza resenas de reservas
-- canceladas, pendientes o que no se han realizado.
-- El cliente y el alojamiento se obtienen a traves de la reserva.
-- ==============================================================================
CREATE TABLE RESENA (
    id_resena NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- PK
    id_reserva NUMBER(8) NOT NULL UNIQUE,
    estado_reserva VARCHAR2(10) DEFAULT 'COMPLETADA' NOT NULL CHECK (estado_reserva = 'COMPLETADA'),
    calificacion NUMBER(1) NOT NULL CHECK (calificacion BETWEEN 1 AND 5),   -- de 1 a 5
    comentario VARCHAR2(500),                                               -- opcional
    fecha_resena DATE NOT NULL,
    CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva, estado_reserva) REFERENCES RESERVA(id_reserva, estado)
);


-- ==============================================================================
-- 14. USUARIO_SISTEMA
-- El personal interno de la plataforma: administradores (no estan atados a ningun
-- alojamiento) y encargados (cada uno administra un solo alojamiento).
-- ==============================================================================
CREATE TABLE USUARIO_SISTEMA (
    id_usuario NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- PK
    username VARCHAR2(30) NOT NULL UNIQUE,
    nombre_completo VARCHAR2(100) NOT NULL,
    correo VARCHAR2(120) NOT NULL UNIQUE,
    rol VARCHAR2(25) NOT NULL CHECK (rol IN ('ADMIN_PLATAFORMA', 'ENCARGADO_ALOJAMIENTO')),
    id_alojamiento NUMBER(5),                                               -- solo lo tienen los encargados
    activo CHAR(1) DEFAULT 'S' NOT NULL CHECK (activo IN ('S', 'N')),
    CONSTRAINT fk_usr_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES ALOJAMIENTO(id_alojamiento),
    -- el encargado SIEMPRE tiene alojamiento y el administrador NUNCA
    CONSTRAINT chk_usr_rol_aloj CHECK ((rol = 'ENCARGADO_ALOJAMIENTO' AND id_alojamiento IS NOT NULL)
                                    OR (rol = 'ADMIN_PLATAFORMA' AND id_alojamiento IS NULL))
);